#ifndef SIMPLEGALLERYCORE_GLOBAL_H
#define SIMPLEGALLERYCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMPLEGALLERYCORE_LIBRARY)
#define SIMPLEGALLERYCORE_EXPORT Q_DECL_EXPORT
#else
#define SIMPLEGALLERYCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMPLEGALLERYCORE_GLOBAL_H
